/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rsa;
import java.math.BigInteger;
import javax.swing.JOptionPane;
import rsa.Rsa;

/**
 *
 * @author miguel
 */
public class RSA extends javax.swing.JFrame {

    /** Creates new form RSA */
    private Rsa rsa;
    private BigInteger[] textoCifrado;
    int bandera=0;
        
    public RSA() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.jbtdescrifrar.setEnabled(false);
        this.jbtcifrar.setEnabled(false);
        this.txtareacifrado.setLineWrap(true);
        this.txtareamensaje.setLineWrap(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txttamanio = new javax.swing.JTextField();
        jbtgenerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareamensaje = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtareacifrado = new javax.swing.JTextArea();
        jbtdescrifrar = new javax.swing.JButton();
        jbtcifrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbtdetalles = new javax.swing.JButton();
        jlbavisos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel1.setText("R  S  A");
        jLabel1.setMaximumSize(new java.awt.Dimension(30, 30));

        jLabel2.setText("Tamaño de bits:");

        txttamanio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttamanioActionPerformed(evt);
            }
        });
        txttamanio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttamanioKeyTyped(evt);
            }
        });

        jbtgenerar.setText("Generar ");
        jbtgenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtgenerarActionPerformed(evt);
            }
        });

        txtareamensaje.setColumns(20);
        txtareamensaje.setRows(5);
        jScrollPane1.setViewportView(txtareamensaje);

        txtareacifrado.setColumns(20);
        txtareacifrado.setRows(5);
        jScrollPane2.setViewportView(txtareacifrado);

        jbtdescrifrar.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jbtdescrifrar.setText("<");
        jbtdescrifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtdescrifrarActionPerformed(evt);
            }
        });

        jbtcifrar.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jbtcifrar.setText(">");
        jbtcifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtcifrarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel5.setText("Mensaje");

        jLabel6.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel6.setText("Cifrado");

        jbtdetalles.setText("Detalles");
        jbtdetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtdetallesActionPerformed(evt);
            }
        });

        jlbavisos.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtcifrar)
                            .addComponent(jbtdescrifrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtdetalles)
                            .addComponent(jlbavisos)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttamanio, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addComponent(jbtgenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtgenerar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtdetalles)
                .addGap(7, 7, 7)
                .addComponent(jlbavisos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtcifrar)
                        .addGap(29, 29, 29)
                        .addComponent(jbtdescrifrar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttamanioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttamanioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttamanioActionPerformed

    private void jbtdescrifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtdescrifrarActionPerformed
        // TODO add your handling code here:
        if( this.txtareacifrado.getText().length()!=0){
            String recuperarTextoPlano = rsa.desencripta(textoCifrado);
            this.txtareamensaje.setText(recuperarTextoPlano);
        }else{
            this.jlbavisos.setText("No hai mensaje a descifrar. Por favor ingrese su mensaje");
        }
    }//GEN-LAST:event_jbtdescrifrarActionPerformed

    private void jbtdetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtdetallesActionPerformed
        // TODO add your handling code here:
        if(this.bandera==1){
            Detalles windows = new Detalles(this,true);
            windows.setVar(rsa.getP(),rsa.getQ(),rsa.getN(),rsa.getE(),rsa.getD(),rsa.getPhi());
            windows.setTexto();
            windows.setVisible(true);
        }
    }//GEN-LAST:event_jbtdetallesActionPerformed

    private void jbtgenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtgenerarActionPerformed
        // TODO add your handling code here:
        if( this.txttamanio.getText().length()!=0){
            if(Integer.parseInt(this.txttamanio.getText())>=2){
                this.jlbavisos.setText("");
                this.bandera=1;
                rsa = new Rsa(Integer.parseInt(this.txttamanio.getText()));
                /*BigInteger x = new BigInteger("1701");
                BigInteger y = new BigInteger("2700");      
                System.out.println(""+x.modPow(new BigInteger("247"),new BigInteger("14317")));
                System.out.println(""+y.modPow(new BigInteger("247"),new BigInteger("14317")));
                
                BigInteger xx = new BigInteger("13684");
                BigInteger yy = new BigInteger("1742");      
                System.out.println(""+xx.modPow(new BigInteger("9403"),new BigInteger("14317")));
                System.out.println(""+yy.modPow(new BigInteger("9403"),new BigInteger("14317")));*/
                
                this.jbtdescrifrar.setEnabled(true);
                this.jbtcifrar.setEnabled(true);
                Detalles windows = new Detalles(this,true);
                windows.setVar(rsa.getP(),rsa.getQ(),rsa.getN(),rsa.getE(),rsa.getD(),rsa.getPhi());
                windows.setTexto();
                windows.setVisible(true);
            }else{
                this.jlbavisos.setText("El numero de bits tiene que ser mayor o igual a 2");
            }
        }else{
            this.jlbavisos.setText("Ingrese el numero de bits");
        }
                
    }//GEN-LAST:event_jbtgenerarActionPerformed

    private void txttamanioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttamanioKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if(Character.isLetter(car)){
            evt.consume();
        }
    }//GEN-LAST:event_txttamanioKeyTyped

    private void jbtcifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtcifrarActionPerformed
        // TODO add your handling code here:
        if( this.txtareamensaje.getText().length()!=0){
            textoCifrado=rsa.encripta(this.txtareamensaje.getText());
            this.txtareacifrado.setText("");
            for(int i=0; i<textoCifrado.length; i++)
                this.txtareacifrado.append(textoCifrado[i].toString());
            
        }else{
            this.jlbavisos.setText("No hai mensaje a cifrar. Por favor ingrese su mensaje");
        }
    }//GEN-LAST:event_jbtcifrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RSA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtcifrar;
    private javax.swing.JButton jbtdescrifrar;
    private javax.swing.JButton jbtdetalles;
    private javax.swing.JButton jbtgenerar;
    private javax.swing.JLabel jlbavisos;
    private javax.swing.JTextArea txtareacifrado;
    private javax.swing.JTextArea txtareamensaje;
    private javax.swing.JTextField txttamanio;
    // End of variables declaration//GEN-END:variables

}
